version: "3.9"
services:

  db:
    container_name: postgres_db_container1
    image: postgres:14.3-alpine3.15
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", pg_isready -U admin -d new_db ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s